apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment  # The name of your deployment
spec:
  replicas: 3  # Run 3 copies of your application for high availability
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app-container
        # --- IMPORTANT: REPLACE THIS LINE ---
        image: us-central1-docker.pkg.dev/your-gcp-project-id/your-repo-name/your-image:tag
        ports:
        - containerPort: 8080 # The port your application listens on inside the container
